from budget import Category
from budget import create_spend_chart

# print(clothing.category+" balance:",clothing.get_balance())

food = Category("Food")
food.deposit(1000, "deposit")
food.withdraw(10.15, "groceries")
food.withdraw(15.89, "restaurant and more food for dessert")
food.withdraw(175.00, "took the entire family to dinner")
clothing = Category("Clothing")
food.transfer(50, clothing)
videogames = Category("Videogames")
hygiene = Category("Hygiene")
clothing.deposit(1000, "deposit")
clothing.withdraw(17.99, "socks")
clothing.withdraw(25.00, "t-shirt")
clothing.withdraw(149.75, "brand new shoes")
clothing.transfer(150.00, videogames)
videogames.deposit(2000, "deposit")
videogames.withdraw(99.99, "videogame cartridge on sale")
videogames.withdraw(200.00, "vintage controller")
hygiene.deposit(500.00, "deposit")
hygiene.transfer(100.00, food)
hygiene.withdraw(19.50, "bathroom products")
hygiene.withdraw(89.99, "facial treatment")
print(food)
print(clothing)
print(videogames)
print(hygiene)
# print(clothing.category+':', clothing.ledger)
# print(food.category+" balance:",food.get_balance())
# print(food.category+':',food.ledger)
categories = [food, clothing, videogames, hygiene]
create_spend_chart(categories)